# Generated by Django 2.0.5 on 2018-05-17 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ddos', '0002_dosresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
