# Generated by Django 2.0.5 on 2018-05-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddos', '0003_dosresult_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosresult',
            old_name='identifer',
            new_name='identifier',
        ),
    ]
