---
# set up the NCDR project itself

- name: Setup the Git repo
  git: repo={{ GIT_REPO }}
       version={{ GIT_BRANCH }}
       dest={{ PROJECT_PATH }}
       accept_hostkey=yes
       force=yes

- name: Delete all .pyc files
  command: find . -name '*.pyc' -delete
  args:
    chdir: "{{ PROJECT_PATH }}"
  tags: git
  changed_when: False

- name: Creates log dir
  file:
    path: "{{ LOG_DIR }}"
    state: directory


- name: Creates config dir
  file:
    path: "{{ CONFIG_DIR }}"
    state: directory

# otherwise it complains silently and
# blows up the world
- name: Creates gunicorn log
  file:
    path: "{{ LOG_DIR }}/gunicorn.log"
    state: touch

- name: Create configs
  template:
    src: "templates/{{ item }}.jinja2"
    dest: "{{ PROJECT_PATH }}/deployment/config/{{ item }}"
    mode: 0744
    owner: root
  with_items:
    - gunicorn.conf
    - gunicorn_conf.py
    - nginx_site.conf

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ VIRTUALENV_PATH }} requirements={{ REQUIREMENTS_FILE }}
  executable: pip3

- name: Create local settings
  template:
    src: "templates/local_settings.py.jinja2"
    dest: "{{ PROJECT_PATH }}/{{ application_name }}/local_settings.py"
    mode: 0744
    owner: root

- name: Run Django database migrations
  args:
    chdir: "{{ PROJECT_PATH}}/{{ application_name }}"
  command: "{{ VIRTUALENV_PATH }}/bin/python manage.py migrate"

- name: Run Django collectstatic
  args:
    chdir: "{{ PROJECT_PATH}}/{{ application_name }}"
  command: "{{ VIRTUALENV_PATH }}/bin/python manage.py collectstatic --noinput"

- name: Remove old nginx default
  become: true
  file:
    state: absent
    path: "/etc/nginx/sites-available/default"

- name: Symlink nginx
  become: true
  file:
    src: "{{ PROJECT_PATH }}/deployment/config/nginx_site.conf"
    dest: "/etc/nginx/sites-available/default"
    owner: root
    group: root
    state: link

- name: Restart nginx
  become: true
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Kill gunicorn
  sudo: yes
  command: "pkill gunicorn"
  ignore_errors: True

- name: Create circus config
  become: yes
  template:
    src: "templates/circus.ini.jinja2"
    dest: "/etc/circus/circusd.ini"

- name: Restart circus
  become: yes
  command: "circusctl restart"
  ignore_errors: True
